---
openapi: 3.0.1
info:
  title: Content API
  description: Content API for KIQR Headless CMS
  version: 0.16.4
paths:
  "/{contentTypeId}/{documentId}/relations/{fieldId}":
    get:
      summary: Returns a list of related documents
      tags:
      - Relationships
      operationId: getRelations
      security:
      - environmentId: []
      parameters:
      - name: contentTypeId
        in: path
        example: frontpage
        required: true
        schema:
          type: string
      - name: documentId
        in: path
        example: doc_zWNY2gOL1xwrYuRqXQnjJZyP
        required: true
        schema:
          type: string
      - name: fieldId
        in: path
        example: featuredPosts
        required: true
        schema:
          type: string
      responses:
        '401':
          description: Query parameter environmentId is missing or invalid
        '200':
          description: Returns a list of related documents
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/DocumentsCollection"
  "/{contentTypeId}/":
    get:
      summary: Returns documents by content type
      tags:
      - Documents
      operationId: getDocuments
      security:
      - environmentId: []
      parameters:
      - name: contentTypeId
        in: path
        example: posts
        required: true
        schema:
          type: string
      responses:
        '401':
          description: Query parameter environmentId is missing or invalid
        '200':
          description: Returns a list of documents
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/DocumentsCollection"
servers:
- url: https://content.kiqr.cloud/v1
components:
  securitySchemes:
    environmentId:
      type: apiKey
      name: environmentId
      in: query
  schemas:
    Document:
      type: object
      additionalProperties: false
      required:
      - id
      - name
      - slug
      - contentType
      - content
      - updatedAt
      - createdAt
      properties:
        id:
          type: string
          example: doc_zWNY2gOL1xwrYuRqXQnjJZyP
        name:
          type: string
          example: My first post
        slug:
          type: string
          example: my-first-post
        contentType:
          type: string
          example: posts
        content:
          type: object
        relations:
          type: object
        updatedAt:
          type: string
          format: date-time
          example: '2023-01-17T09:36:08Z'
        createdAt:
          type: string
          format: date-time
          example: '2023-01-17T09:36:08Z'
    DocumentsCollection:
      type: object
      required:
      - documents
      - meta
      properties:
        documents:
          type: array
          items:
            "$ref": "#/components/schemas/Document"
        meta:
          type: object
          required:
          - pagination
          properties:
            pagination:
              "$ref": "#/components/schemas/PaginationMeta"
    PaginationMeta:
      type: object
      additionalProperties: false
      required:
      - count
      - page
      - items
      - pages
      properties:
        count:
          type: number
          example: 26
        page:
          type: number
          example: 2
        items:
          type: number
          example: 20
        pages:
          type: number
          example: 2
        from:
          type: number
          example: 21
        to:
          type: number
          example: 26
