---
openapi: 3.0.1
info:
  title: Content API
  description: Content API for KIQR Headless CMS
  version: 0.4.1
paths:
  "/resources":
    get:
      summary: List resources
      tags:
      - Resources
      operationId: getResources
      security:
      - api_key: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: number
      - name: content_type
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: resources scoped by content_type
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourcesResponse"
        '401':
          description: unauthorized
    post:
      summary: Create a resource
      tags:
      - Resources
      operationId: createResource
      security:
      - kiqr_identity: []
      parameters: []
      responses:
        '201':
          description: create a resource
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Resource"
        '422':
          description: with validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
                content_type:
                  type: string
                locale:
                  type: string
                content:
                  type: object
              required:
              - name
              - content_type
        required: true
  "/resources/{id}":
    get:
      summary: Retrieve a resource
      tags:
      - Resources
      operationId: getResource
      security:
      - api_key: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: locale
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: a translation of a resource
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Resource"
        '401':
          description: unauthorized
servers:
- url: https://content-api.kiqr.cloud/v1
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
    kiqr_identity:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Resource:
      type: object
      required:
      - id
      - environment_id
      - locale
      - name
      - slug
      - content_type
      - updated_at
      - created_at
      properties:
        id:
          type: string
          format: uuid
          example: 1a279ed7-2a60-4281-bb70-707d6cf5d393
        environment_id:
          type: string
          format: uuid
          example: 851318d9-e3b6-40fb-80e9-e76b57057af0
        locale:
          type: string
          example: en
        name:
          type: string
          example: My first post
        slug:
          type: string
          example: my-first-post
        content:
          type: object
        content_type:
          type: string
          example: posts
        user_id:
          type: string
          format: uuid
          example: 4779f4e9-96cb-4c00-9400-f9d71e4a635d
        updated_at:
          type: string
          format: datetime
          example: '2021-01-30T08:30:00Z'
        created_at:
          type: string
          format: datetime
          example: '2021-01-30T08:30:00Z'
      additionalProperties: false
    ResourcesResponse:
      type: object
      required:
      - data
      - meta
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/Resource"
        meta:
          type: object
          required:
          - pagination
          properties:
            pagination:
              type: object
              required:
              - count
              - page
              - items
              - pages
              - from
              - to
              properties:
                count:
                  type: number
                  example: 32
                page:
                  type: number
                  example: 1
                items:
                  type: number
                  example: 20
                pages:
                  type: number
                  example: 2
                from:
                  type: number
                  example: 21
                to:
                  type: number
                  example: 26
