---
openapi: 3.0.1
info:
  title: Core API
  description: Core API for KIQR Headless CMS
  version: 0.3.0
paths:
  "/":
    get:
      summary: Welcome message
      tags:
      - Welcome
      responses:
        '200':
          description: Returns a welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: KIQR Content API
                  apiVersion:
                    type: integer
                    example: 1
                  engineVersion:
                    type: string
                    example: 1.0.0
servers:
- url: https://api.kiqr.cloud/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
